version: "3.9"

services:

  postgres-tp:
    build: ./postgresql
    container_name: devops_postgres-tp_1
    volumes:
      - ./postgresql/data:/var/lib/postgresql/saved-data
      - ./postgresql/pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-network
      
  backend-tp-1:
    build: ./backend
    container_name: devops_backend-tp_1
    networks:
      - app-network
    depends_on:
      - postgres-tp
  
  backend-tp-2:
    build: ./backend
    container_name: devops_backend-tp_2
    networks:
      - app-network
    depends_on:
      - postgres-tp
      
  httpd-tp:
    build: ./httpd
    container_name: devops_httpd-tp_1
    ports:
     - 80:80
     - 8080:8080
    networks:
      - app-network
    depends_on:
      - postgres-tp
      
  frontend-tp:
    build: ./front
    container_name: devops_frontend-tp_1
    networks:
      - app-network
    depends_on:
      - httpd-tp
    
networks:
  app-network:
    name: app-network
