version: "3.9"

services:

  postgres-tp:
    build: ./postgresql
    container_name: devops_postgres-tp_1
    volumes:
      - ./postgresql/data:/var/lib/postgresql/saved-data
      - ./postgresql/pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-network
      
  backend-tp:
    build: ./backend
    container_name: devops_backend-tp_1
    networks:
      - app-network
    depends_on:
      - postgres-tp
      
  frontend-tp:
    build: ./frontend
    container_name: devops_frontend-tp_1
    ports:
      - 80:80
    networks:
      - app-network
    depends_on:
      - postgres-tp
    
networks:
  app-network:
    name: app-network
